### Random Forest aus SkLearn


In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import ensemble

# Einlesen der Daten
data = pd.read_csv("output.csv", index_col=0)
data_burghart = pd.read_csv("output_burghart.csv", index_col=0)

# Entfernen von Spalten, die nicht für die Klassifikation benötigt werden
X = data.iloc[:, :-1].values
Y = data.iloc[:, -1].values.reshape(-1, 1)
X_burghart_test = data.iloc[:, :-1].values
Y_burghart_test = data.iloc[:, -1].values.reshape(-1, 1)

# Aufteilen in Trainings- und Testdaten
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1234)

# random-Forest-Modell initialisieren und trainieren
RF_classifier = ensemble.RandomForestClassifier() #Klassifikator initialisieren mnit Standardparametern (100 trees, gini criterion)
RF_classifier.fit(X_train, Y_train)

# Vorhersagen für Testdaten treffen
Y_pred = RF_classifier.predict(X_test) 
Y_burghart_pred = RF_classifier.predict(X_burghart_test)

c:\Users\hanne\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


In [3]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import numpy as np

# acc = Anzahl vorhergesagte Klassen die der echten Klasse entsprechen / Gesamtanzahl
acc = accuracy_score(Y_test, Y_pred)
acc_burghart = accuracy_score(Y_burghart_test, Y_burghart_pred)

print("Accuracy score:         ", acc)
print("Accuracy score burghart:", acc_burghart)

# Ausgabe der Konfusion Matrix 
print('\nconfusion matrix:')
print(confusion_matrix(Y_test, Y_pred),'\n')

# Ausgabe des Classifikation Report
print(classification_report(Y_test, Y_pred))

# Precision = Prozentsatz der korrekt positiven Vorhersagen zu allen positiven Vorhersagen  (True Positives/ all predicted Positives)
# recall    = Prozentsatz der korrekt positiven Vorhersagen zu allen tatsächlich Positiven  (True Positives/ all real Positives)
# f1-score  = Mittelwert aus Precision und Recall                                              

Accuracy score:          0.879154078549849
Accuracy score burghart: 0.9758088902328395

confusion matrix:
[[178   2  36]
 [  6 135   8]
 [ 23   5 269]] 

              precision    recall  f1-score   support

           0       0.86      0.82      0.84       216
           1       0.95      0.91      0.93       149
           2       0.86      0.91      0.88       297

    accuracy                           0.88       662
   macro avg       0.89      0.88      0.88       662
weighted avg       0.88      0.88      0.88       662

